# Generated by Django 2.2.6 on 2019-11-29 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='adventure',
            name='name',
            field=models.CharField(default='epworth', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='adventure',
            name='price',
            field=models.FloatField(default=50),
            preserve_default=False,
        ),
    ]
