# Generated by Django 2.2.6 on 2020-01-30 18:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_booking_event'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adventure',
            name='price',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='adventure',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='number_of_participants',
        ),
        migrations.AddField(
            model_name='booking',
            name='email',
            field=models.EmailField(default='test@nullmail.com', max_length=254),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='PriceSchedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('participants', models.PositiveSmallIntegerField()),
                ('adventure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Adventure')),
            ],
        ),
        migrations.CreateModel(
            name='BookingLine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_participants', models.IntegerField()),
                ('adventure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Adventure')),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Booking')),
            ],
        ),
    ]
