# Generated by Django 2.2.6 on 2020-01-30 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20200130_2054'),
    ]

    operations = [
        migrations.AddField(
            model_name='priceschedule',
            name='price',
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
    ]
